name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]



env:
  DATA_CONTENT: 'demo_charla'
  DATA_SCANS: '/tmp/scans'
  SLACK_CHANNEL: 'builds-and-ci'
  SLACK_MSG_COLOR: '#0092ff'
  COMMITER_NAME: 'AutoCommit'

  VULN_SEVERITY: 'CRITICAL'
  VULN_TYPE: 'os,library'
  VULN_FORMAT: 'table'
  VULN_TIMEOUT_SCAN: '2m0s'
  VULN_SCANNERS: 'vuln,secret,misconfig,license'
  VULN_IGNORED_LIC: 'MIT' # MIT,LGPL,MPL-2.0
  VULN_EXIT_CODE: 1
  TRIVY_DISABLE_VEX_NOTICE: true

jobs:

  DevSecOps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          
      - name: show data
        run: |
          apt-get update; apt-get install tree -y
          ls -lha ${{ env.DATA_CONTENT }}
          tree -a

      - name: Run Trivy
        run: |
          docker run --rm -v ${{ env.DATA_CONTENT }}:/project zricethezav/gitleaks detect -v --source=/project --exit-code 0
          
